name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pedropucrs
          password: Senha@2024

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pedropucrs/agency-image:latest

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----MIIEpAIBAAKCAQEAm5Aq4VbQt/y8VsJ4Di+d7b3UL+7j0Fgtu7VpvIIwo3VR0xgsIUtfqbwiCl6hCIkfLS71ASwTqUF3vgs+NFlPwymPTDAbuDZwqcY0QEV7dSxwBg1rnKrjyRJVzLrsOt4nsgTL7FBWZTzNarRXc/hwjwAqtqf6e0MDHb6eZYUWVUSvuTtE07s2H6HMNfqHfRvuaoJGkCy78Gvrzc2Km7eVsu5EmeS+1LxfPa3JjV4vkZo0tOYQ1KEtcT1WtBgc18/YeNPw6thrangYH9HHSWzp/SM9aYmxSNBLU3zXDE3IxvwwLysxDCFPIn/Rm3fyXEZvR1arXfWp7vXoqwSGDfltwQIDAQABAoIBAA0fv45dPaSYDOeg5nID8GXzQuh8Vfnoxor0hiQiM6pGpo2Rl3+DlWGDfrezPhCzSM8ODBt6NXptDIYa+rd95W3Ins9Fq8EBzsVz9EqL0huTkSvhi/eerzLyegyYpH9e6KhrIS0hpfhKheX/qvUcu5pE4FWinE4z3BpxT3mvHbA5xnwsHg0F/0vJAyxzpo8ciRF7lYnCF7Q0J0vaqPlM6/80a48o7JovJHogULUVHBG53CF4EKe6+nA824jwczg3RKZfhVwpXhaAOF0mQYc7BnLu4B12wK4k4Wx8Iy1v5WsEtU9pxT8VKETa2iygqyeqBLLB//B08hGnjbJtaCuPRcECgYEA1g+PkDzsVb+nn4TVOWJ0MGjwwoo/tL4DgI2Z6+TmWoBfgAw0Z5uM07fC4Mlnd3OWzIOvU5S/6Pr0MTg7W8tB6tgZcnZ61+ABhmRe4OtjzBh7dw4XxHDRLGfUl1RlCUcHFQFLhDIAnJdSLR9LzGJMG6tbF5JsgB8jsNqVwuh8J0kCgYEAugqZCSD4EeGPc7Jbkdqdu5j9ZZZbV79bD57APru65nXQbxnGNLlQNABNNvMzFs+g4mmZil+0t74KAH+dCT+OTgs2r7veDQqoQcCyz4Sr7VM1OR9aHp9YFevRAntAQ6XTeef0evIvizu4OJSsUgo4uVf65ZaeZCuD5/3ZdYwGurkCgYEArlH5vaJ/a80pulQ4OAUfTZUIC8T94DilLXkjEeFUXfsQynwl6QHZi0iooNojMjmlYmMS0mPebOKBHdwHKte5lH/rKTWnEEnRtBnk0hGfMcP2N5v4avbcwObFT39g0E9RSx/E2aDGsr7gIvLLjWO3Swkeo3GQfj3dmNZJA3LEOFECgYEAtkQRwJbTUzloQJJ6EgBbzmJJx9Ax91rbTQdcE1n69zRvm5llzVvMztWI0JAd+ng6h/erXJz9QZLm26wq3teshJuJ3UuydZZ+V8UBqjux8RY3K5qiwSOdugRJxiOYR25cLK/qntVNbRx6FLzbwpiPEE642VviHANh/NR/yyD/qskCgYBEeqxY1pSz1HXZLGXVwTErHeYQpP1omwPrsOta9LzCUgakGD72k1CVa0SXFcdBe+IYy69W56WBwyjxsu1F5Qqa/QSX0f1o6hDz1xX6yoS8/5QwZnVFeD7a0l3chbKpH8Bq5XRuVu4H30+/OcraiXqvttyQdPxLms6+wAAOFHUAZA==-----END RSA PRIVATE KEY-----
          HOST: ec2-34-203-210-23.compute-1.amazonaws.com
          USERNAME: ec2-user
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" $USERNAME@$HOST << 'EOF'
          if ! command -v docker &> /dev/null
            then
              echo "Docker not found, installing..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USERNAME
            fi

            docker pull pedropucrs/agency-image:latest
            docker stop agency-container || true
            docker rm agency-container || true
            docker run -d --name agency-container -p 8080:8080 pedropucrs/agency-image:latest
          EOF
